---
title: Climate Change and Complexity in Classical Liberal Theories of Development
lang: en-GB
description: In this essay, I develop a complexity-based theory of social interaction
  within legal constraints, highlighting how rule-of-law institutions enable cooperation
  even in the face of intricate political and economic pressures based on inequities
  in mitigating and preparing for climate change..
legacy:
  title: Climate Change and Complexity in Classical Liberal Theories of Development
  collection: publications
  author: James Kennon Rice
  category: working_papers
  excerpt: In this essay, I develop a complexity-based theory of social interaction
    within legal constraints, highlighting how rule-of-law institutions enable cooperation
    even in the face of intricate political and economic pressures based on inequities
    in mitigating and preparing for climate change..
  date: '2025-02-01'
  venue: Working Paper
  citation: Rice, James Kennon. (2025). &quot;Climate Change and Complexity in Classical
    Liberal Theories of Development.&quot; <i>Work in Progress</i>.
---


```{=html}
<div class="record-meta">James Kennon Rice<br>Working Paper<br>2025-02-01</div>
```

By focusing on "simple rules for a complex world," I show how government-imposed constraints, when guided by stable and equally applicable frameworks, can help shape group agency and collective choice. Regulated choice, I argue, is essential to tackling social and environmental externalities caused by human action - such as climate change. My conclusion will argue that stochastic shocks which originate in natural phenomena caused, indirectly, by humans (i.e., climate change), impair efforts for international development, and create additional feedback loops which slow progress in social justice, global inequality, and international cooperation on issues like the environment between countries at varying levels of wealth and income.

## Citation

Rice, James Kennon. (2025). &quot;Climate Change and Complexity in Classical Liberal Theories of Development.&quot; <i>Work in Progress</i>.
