---
title: Curriculum vitae
lang: en-GB
toc: true
css: cv.css
---

[Updated 27 September 2026]{.cv-updated}

## Education

- **Ph.D. in Government** — *University of Essex*  
  October 2024–October 2027 *(expected)*.
- **MSc in the Philosophy of the Social Sciences** — *London School of Economics and Political Science*  
  September 2023–August 2024.
- **MSc in Philosophy, Science and Religion** — *University of Edinburgh*  
  September 2022–August 2023.
- **Postgraduate Certificate in Philosophy and Ethics** — *Harvard Extension School*  
  June 2021–May 2022.
- **Bachelor of Science in Economics** — *University of Connecticut*  
  August 2018–May 2020.
- **Environmental and Resource Economics major; Political Science minor** — *University of New Hampshire*  
  August 2014–May 2017. Transferred to the University of Connecticut in Fall 2018.

## Work experience & teaching {#work-experience}

- **Fixed-Term Lecturer in Computational Social Science** — *University of Essex, Department of Sociology and Criminology*  
  October 2026–Present.
  - *Introduction to Social Data Science* — **SC207**, Autumn 2026.
- **Teaching Assistant** — *UCL Department of Political Science*  
  September 2026–Present. Undergraduate courses:
  - *Data Analysis* — **POLS0010**, Spring 2027.
  - *Ethics and Public Policy* — **POLS0064**, Fall 2027.
- **Mercatus Fellowship** — *The Mercatus Center at George Mason University*  
  August 2026–Present. Applied Mainline Political Economy.
- **Teaching Assistant** — *Essex Summer School in Social Science Data Analysis*  
  July 2026. Postgraduate courses:
  - *Applied Causal Inference with Observational Data*.
  - *Causal Inference and Experiments in the Social Sciences*.
- **Research Assistant for Professor Tobias Bohmelt** — *University of Essex, Department of Government*  
  April 2026–September 2026.
- **Policy Fellowship** — *Council for Countering Online Disinformation (CCOD)*  
  April 2026–September 2026.
- **Teaching Assistant** — *UCL Department of Political Science*  
  January 2026–June 2026. Undergraduate courses:
  - *Introduction to Quantitative Research Methods* — **POLS0008**, Spring 2026.
  - *Science, Scientific Discovery and Statistics* — **POLS0060**, Spring 2026.
- **Research Affiliate** — *LSE Hayek Programme in Liberal Political Economy*  
  January 2026–Present.
- **Research Fellowship** — *Earth System Governance Project*  
  November 2025–Present.
- **Ronald Coase Fellowship** — *The Mercatus Center at George Mason University*  
  August 2025–August 2026.
- **Teaching Assistant** — *Essex Summer School in Social Science Data Analysis*  
  July 2025–August 2025. Postgraduate courses:
  - *Introduction to Quantitative Text Analysis*.
  - *Quantitative Data Analysis and Statistical Graphics with R*.
- **Research Associate in Online Moral Contagion** — *Oxford Computational Political Science Group, Oxford Internet Institute (OII)*  
  March 2025–March 2026.
- **Frédéric Bastiat Fellowship** — *The Mercatus Center at George Mason University*  
  September 2023–June 2024.

## Publications

- **[The Epistemic Frontier of Capitalism: A Theory of Epistemic Regression through Artificial Intelligence and Misinformation](/publications/epistemic_frontier_capitalism/)**  
  *The Cambridge Journal of Artificial Intelligence* — July 2026.
- **[The Liberal Order in Complex Societies Marred by Climate Change](/publications/liberal_order_complex_societies_climate_change/)**  
  *Review of Evolutionary Political Economy* — May 2026.
- **[Beyond Post-Truth: Projecting the Future Trajectory of Climate Misinformation](/publications/Beyond_post_truth_climate_misinformation/)**  
  *PLOS Climate* — May 2026.
- **[The Misinformation Challenge: How Information Freedom Promotes Democratic Discourse](/publications/misinformation_challenge_information_freedom/)**  
  *Journal of Libertarian Studies* — January 2026.
- **[Knowledge Asymmetries and Climate Finance: An Inquiry into Environmental Market Failures and Political Legitimacy](/publications/Knowledge_asymmetries_climate_finance/)**  
  *The Cambridge Journal of Climate Research* — December 2025.
- **[The Prospect of ‘Just Emissions’ as an International Norm of Environmental Governance](/publications/Just_emissions/)**  
  *The Cambridge Journal of Climate Research* — December 2024.

## Other publications

- **[Digital Resilience in the Age of Synthetic Media](/writing/digital-resilience-in-the-age-of-synthetic-media/)**  
  *The Loop: European Consortium for Political Research Blog* — February 2026.
- **[How Social Media and Online Communities Influence Climate Change Beliefs](/writing/the-loop/)**  
  *The Loop: European Consortium for Political Research Blog* — March 2025.
- **[The Smart Era](/files/james-rice-the-smart-era-portfolio.pdf)**  
  *Digital Frontier Magazine* — March 2025.
- **[An Ecological Ethics for the Anthropocene: A Call to Reimagine Religion and Nature](/writing/ecological-ethics/)**  
  *LSE Religion and Global Society Blog* — January 2025.
- **[Studying Through Adversity: How Equity, Diversity and Inclusion Works at LSE](/writing/studying-through-adversity/)**  
  *Students@LSE Blog* — May 2024.

## Working papers

- **Stochastic Deep Learning: A Probabilistic Framework for Modeling Uncertainty in Structured Temporal Data**.
- **Modeling Infrastructure and Climate from the World Bank’s Enterprise Surveys**.
- **Interdisciplinarity in International Sustainable Business**.
- **International Norms of Environmental Governance: The Transnational Management of Developmental and Ecological Justice**.
- **The Social Justification of Climate Change Beliefs and Environmental Communication**.

## Further academic study

- **UCL Teaching Associate Programme (TAP)** — May 2026.  
  Completed UCL’s *PGTA teaching training course* in preparation for an AFHEA application.
- **Oxford University Economics Summer School** — September 2025.  
  Completed two courses in *Machine Learning* and *Behavioral Macroeconomics*.
- **LSE Faith Centre and Cambridge University InterFaith Programme** — July 2024.  
  Summer School on *Religion and Climate Futures*.
- **LSE Faith Centre Beecken Faith and Leadership Programme** — January–March 2024.  
  Segments on *Religion and Climate Change* and *Conflict Transformations*.
- **Utrecht University** — August 2021.  
  Summer School on *The Posthuman and New Materialist Philosophy*.
- **New England Complex Systems Institute** — January 2020.  
  Winter School in *Complex Systems Science*.
- **London School of Economics and Political Science** — June 2018–August 2018.  
  Summer School in *Advanced Econometrics and Statistics*.
- **United Nations Institute for Training and Research** — January 2018–June 2018.  
  *International Relations and Global Diplomacy Graduate Diploma*.
- **University of New Hampshire** — May 2017–August 2017.  
  *UNH Social Innovation Intern*.

## Conference & seminar presentations {#talks}

### University of Essex

- **Does Climate Misinformation Exacerbate Information Asymmetry?**  
  *ECPR General Conference* — September 2026.
- **From Doctoral Training to Academic Leadership Invited Panel**  
  *ISA Virtual Conference* — July 2026.
- **Does Climate Misinformation Exacerbate Information Asymmetry?**  
  *ISA Virtual Conference* — July 2026.
- **Does Climate Misinformation Exacerbate Information Asymmetry?**  
  *SASE General Conference* — July 2026.
- **Does Climate Misinformation affect ESG Performance**  
  *EPSS Annual Conference* — June 2026.
- **Does Climate Misinformation Exacerbate Information Asymmetry?**  
  *Essex Sustainable Transitions Annual Conference* — June 2026.
- **Neural SDEs for Finance and Asset Pricing**  
  *JARGON (Essex Internal Seminar)* — June 2026.
- **SCAIRY BioYUFE Adaptation Invited Panel**  
  *BioYUFE Webinar* — June 2026.
- **Does Climate Misinformation Exacerbate Information Asymmetry?**  
  *JARGON (Essex Internal Seminar)* — December 2025.
- **Does Climate Misinformation Affect ESG Performance?**  
  *Climate, Finance, and Economic Sustainability Workshop, University of Leicester* — December 2025.
- **Cutting Edge Artificial Intelligence Research**  
  *HEROES (Essex Internal Seminar)* — November 2025.
- **Panel Talk on Climate Misinformation**  
  *BioYUFE Meeting (Essex)* — September 2025.
- **Does Climate Misinformation Affect ESG Performance?**  
  *EBS Research Conference (Essex)* — September 2025.
- **Are Religious Political Actors Constrained by Political Neutrality?**  
  *ECPR General Conference* — August 2025.
- **The Effect of Climate Misinformation on Markets and Policy**  
  *ClimateNLP Seminar* — August 2025.
- **Literature Gaps in Moral Contagion Theory**  
  *Oxford OCPSG Internal Presentation* — July 2025.
- **Structural Incentives in Complex Societies Marred by Climate Change**  
  *Association of Heterodox Economics Annual Conference* — June 2025.
- **Climate Discourse and ESG Performance in the Post-Truth Era**  
  *Essex Sustainable Transitions Annual Conference* — June 2025.
- **The Effect of Climate Misinformation on Climate Policy Uncertainty**  
  *Essex Government Department PEPSI Seminar* — March 2025.
- **Frontier Methods in Political Methodology**  
  *HEROES (Essex Gov Internal Seminar)* — January 2025.
- **An Ecological Ethics for the Anthropocene**  
  *Science and Religion Forum Annual Conference* — November 2024.
- **International Norms of Environmental Governance**  
  *Essex Government Conflict Seminar* — November 2024.

### London School of Economics and Political Science

- **The Social Construction of Religious Political Morality**  
  *LSE MSc Dissertation Seminar* — May 2024.
- **Political Liberalism and Moral Pluralism**  
  *Political Philosophy of Environmental Change Classroom Seminar* — November 2023.

### University of Edinburgh

- **Darwin and Natural Theology**  
  *Life and Mind Classroom Seminar* — February 2023.

### Harvard Extension School

- **St. Augustine’s Confessions**  
  *HES Graduate Student Association Conference* — December 2021.

### University of Connecticut

- **American Derivative Securities**  
  *Ph.D. Econometrics III Course Seminar* — April 2020.
- **Using Machine Learning for Macroeconomic Prediction**  
  *UConn Economics Society* — February 2020.
- **Stabilizing Monetary Policy In an Uncertain World**  
  *Boston Federal Reserve University Challenge* — November 2019.

## Reviewing

**Reviewer for:**

- *PLOS Climate*.
- *Open Economies Review*.

## Awards

### University of Essex

- **Mercatus Center Mercatus Fellowship** — **US$2,500**, August 2026.
- **Mercatus Center Ronald Coase Fellowship** — **US$1,750**, August 2025.
- **ECPR General Conference Grant** — **£500**, August 2025.
- **Leverhulme Sustainable Transitions PhD Scholarship** — October 2024–October 2027.

### London School of Economics and Political Science

- **LSE Faith Centre “Religion and Climate Futures” Summer School** — **£1,500**, July 2024.
- **LSE CIVICA Warsaw Sport and Culture Festival** — **£1,000**, June 2024.
- **Mercatus Center Frédéric Bastiat Fellowship** — **US$5,000**, 2023–2024.

### University of Connecticut

- **Charles Triano Scholarship**, *UConn Economics Department* — **US$1,000**, May 2020.
- **UConn Economics Department General Scholarship** — **US$1,000**, April 2019.

### University of New Hampshire

- **Dean’s List** — Spring 2016.
- **Dean’s List** — Fall 2016.

## Community involvement {#service-and-leadership}

### University of Essex

- **Student Member** — *Society for the Advancement of Socio-Economics (SASE)*  
  May 2026–Present.
- **Student Member** — *European Political Science Society (EPSS)*  
  March 2026–Present.
- **Student Member** — *European Consortium for Political Research (ECPR)*  
  October 2024–Present.
- **Student Member** — *American Association for Public Opinion Research (AAPOR)*  
  October 2024–October 2025.
- **Student Member** — *American Political Science Association (APSA)*  
  October 2024–Present.
- **Student Member** — *International Political Science Association (IPSA)*  
  October 2024–October 2025.

### London School of Economics

- **Student Member** — *The Hume Society*  
  April 2024–June 2026.
- **Student Member** — *Science and Religion Forum*  
  April 2024–January 2026.
- **Mentee** — *Career Accelerator Neurodiversity and Disability Mentoring Programme*  
  May 2024–August 2024.
- **Organizing Member** — *LSE Philosophy Minorities and Philosophy (MAP) Group*  
  September 2023–September 2024.
- **Member** — *LSE Philosophy Society*  
  September 2023–September 2024.
- **Member** — *LSE Hayek Society*  
  September 2023–September 2024.
- **Member** — *LSE Effective Altruism (EA) Society*  
  September 2023–September 2024.

### Harvard Extension School / University of Edinburgh

- **Member** — *The Philosophy, Politics, and Economics Society (PPE Society)*  
  January 2023–Present.
- **Member, NYC Chapter** — *United Nations Association of The United States*  
  January 2021–January 2025.
- **Youth Member / Participant** — *YOUNGO Youth Constituency to the UNFCCC*  
  February 2021–January 2022.

### University of Connecticut

- **Member and Lead Administrator** — *Omicron Delta Epsilon, UConn Honor Society in Economics*  
  April 2019–May 2020.
- **President** — *UConn Economics Society*  
  November 2019–May 2020.
- **UConn Fed Challenge Team** — September 2019–May 2020.  
  Presented original macroeconomic research at the *Federal Reserve Bank of Boston*.
- **Social Media Chair** — *UConn Women and Minorities in Economics Society*  
  January 2019–November 2019.

### University of New Hampshire

- **UNH Model United Nations Team** — September 2015–May 2017.  
  Participant in *Model UN ECOSOC negotiations* at the New York City Conference in Spring 2016 and Spring 2017.

## Skills

- **Programming:** *R, Python, LaTeX*.
- **Version control:** *Git and GitHub*.
- **Other tools:** *Microsoft Office*.
