---
title: Interdisciplinarity in International Sustainable Business
lang: en-GB
description: This essay proposes that international business - characterized most
  prominently by the multinational corporation (MNC) - is defined by the types of
  social problems it wishes to solve. It is also defined by the manner, strategy,
  or approach that it uses to define the problem landscape and technological or product-related
  solution space.
legacy:
  title: Interdisciplinarity in International Sustainable Business
  collection: publications
  author: James Kennon Rice and Charles Mensah
  category: working_papers
  excerpt: This essay proposes that international business - characterized most prominently
    by the multinational corporation (MNC) - is defined by the types of social problems
    it wishes to solve. It is also defined by the manner, strategy, or approach that
    it uses to define the problem landscape and technological or product-related solution
    space.
  date: '2025-02-01'
  venue: Working paper with Charles Mensah
  citation: Rice, James Kennon and Mensah, Charles. (2025). &quot;Interdisciplinarity
    in International Sustainable Business.&quot; <i>Work in Progress</i>.
---


```{=html}
<div class="record-meta">James Kennon Rice and Charles Mensah<br>Working paper with Charles Mensah<br>2025-02-01</div>
```

Extensive recent work in interdisciplinary approaches to international business, management, strategy, and marketing, fields characterized by normative efforts to solve so-called ‘grand challenges’, has culminated in a field that is both diverse in its aims and scope, yet which remains insular and sheltered from criticism by outsiders to the profession. In order to overcome these challenges endemic to the field, including within studies of management, strategy, and firm-level microeconomics, interdisciplinary scholars of the firm must engage with allied social sciences as well as field-specific, exemplary natural and applied sciences pertinent to variegated business models in an array of sectors, in order to be useful to practitioners and provide insight to theorists of management and organizations. An important area in this field is sustainability research within the modern firm. Sometimes categorized under the moniker ‘corporate social responsibility’, CSR, or in its form applying to portfolio theory and investment, ‘environmental, social, and governance’ (ESG), these strategies are necessary additions to management, accounting, and strategy disciplines within interdisciplinary international business both because of the paucity of work which addresses them concurrently, as well as because of the complexity of related and interconnected factors that play a role in shaping research and practice in these areas.

## Citation

Rice, James Kennon and Mensah, Charles. (2025). &quot;Interdisciplinarity in International Sustainable Business.&quot; <i>Work in Progress</i>.
